language: node_js # Or any other language that suits your build environment
node_js:
  - 13

services:
  - docker


# Build and push Docker images
script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend:local ./udagram-frontend
  
  - docker tag reverseproxy haihpse150218/reverseproxy:latest
  - docker tag udagram-api-user haihpse150218/udagram-api-user:latest
  - docker tag udagram-api-feed haihpse150218/udagram-api-feed:latest
  - docker tag udagram-frontend:local haihpse150218/udagram-frontend:latest


# Log in to Docker Hub and push images
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push haihpse150218/reverseproxy
  - docker push haihpse150218/udagram-api-user
  - docker push haihpse150218/udagram-api-feed
  - docker push haihpse150218/udagram-frontend:latest

# Optional: Define environment variables
# env:
#   global:
#     - DOCKER_USERNAME=haihpse150218
#     - DOCKER_PASSWORD=
